import type { Lang } from './types'
const en = {
  home: 'Home', services: 'My Services', track: 'Track Tasks', help: 'Help', tagline: 'Your everyday service companion', badge: 'Trusted service guidance',
  exampleElectricity: 'Electricity bill', exampleLicence: 'Licence renewal', examplePan: 'PAN help', voiceInput: 'Use voice input', listening: 'Listening', uploadDocument: 'Upload document', send: 'Search', inputError: 'Please describe what you need help with.', attached: 'Attached',
  newChat: 'New chat', chatHistory: 'Chat history', aiName: 'LifeOS AI', chatWelcome: 'Tell me what you need help with. I can guide you through supported public services.', chatReply: 'I can help you understand the next steps for this request. Continue to the service guidance to see the matching process and action plan.', continueGuidance: 'Continue to service guidance',
  h1: "Tell us what you need. We'll help you find the way.", sub: 'Describe your problem in your own words. LifeOS helps you understand the right official service, required documents and next steps.', ph: 'What are you trying to accomplish?', tryTxt: 'Try saying',
  popular: 'Popular Services', pickService: 'Pick one, or describe your problem above.', howWorks: 'How LifeOS works', fromGoal: 'From your goal to completion, one step at a time.', nextStep: 'Your next step', trackServices: 'Track your services and see what to do next.',
  actionPlan: 'Your Action Plan', complete: 'Complete', myLifeOS: 'My LifeOS', activeServices: 'Active services', pendingActions: 'Pending Actions', completed: 'Completed', upcoming: 'Upcoming',
  noActive: 'No active services yet.', startOne: 'Start one', status: 'Status', inProgress: 'In Progress', pending: 'Pending', next: 'Next', allDone: 'All done', continue: 'Continue',
  documents: 'Documents:', markDone: 'Mark as done', undo: 'Undo', backServices: 'My services', backToServices: 'Back to services', createPlan: 'Create Action Plan', addedServices: 'Added to My Services',
  addToServices: 'Add to My Services', officialService: 'View Official Service', recommended: 'Recommended next steps', requiredInfo: 'Required information', estimatedTime: 'Estimated time', mode: 'Mode', online: 'Online', demoOnly: 'Demo only',
  documentQuestion: 'Have your document?', upload: 'Upload PDF / JPG / PNG', optionalDoc: 'Optional. Nothing leaves your browser in this prototype.', documentReceived: 'Document received', documentAnalyzed: 'Document analyzed', consumerNumber: 'Consumer Number', billAmount: 'Bill Amount', billPeriod: 'Bill Period', remove: 'Remove',
  noNotifications: 'No notifications yet.', resetDemo: 'Reset demo', goHome: 'Go to home', backHome: 'Back to home', language: 'Language',
  flow1: 'Tell us your goal', flow2: 'We find the right official process', flow3: 'We create your action plan', flow4: 'Track it until completion',
  helpBody: 'Type your problem in the box on the home page, or tap a suggestion. LifeOS shows the official process, builds a checklist and lets you track it.',
  notFoundHeading: "We couldn't match this yet", notFoundBody: 'This prototype demonstrates electricity, driving licence and PAN flows. Please try one of those.',
  understanding: 'Understanding your request…', readMessage: 'Reading your message', identifyService: 'Identifying the service', checkProcess: 'Checking relevant official process', preparePlan: 'Preparing your action plan',
} as const
type Key = keyof typeof en
const hi: Partial<Record<Key, string>> = {
  home: 'होम', services: 'मेरी सेवाएं', track: 'कार्य ट्रैक करें', help: 'सहायता', tagline: 'आपका रोज़मर्रा का सेवा साथी', badge: 'भरोसेमंद सेवा मार्गदर्शन', h1: 'बताइए आपको क्या चाहिए। हम रास्ता दिखाएंगे।', sub: 'अपनी समस्या अपने शब्दों में बताइए। LifeOS सही सेवा, ज़रूरी दस्तावेज़ और अगले कदम समझाता है।', ph: 'आप क्या करना चाहते हैं?', tryTxt: 'ऐसे कहें',
  exampleElectricity: 'बिजली का बिल', exampleLicence: 'लाइसेंस नवीनीकरण', examplePan: 'PAN सहायता', voiceInput: 'आवाज़ से बोलें', listening: 'सुन रहे हैं', uploadDocument: 'दस्तावेज़ अपलोड करें', send: 'खोजें', inputError: 'कृपया बताएं कि आपको किस काम में मदद चाहिए।', attached: 'संलग्न',
  newChat: 'नई बातचीत', chatHistory: 'बातचीत का इतिहास', aiName: 'LifeOS AI', chatWelcome: 'बताइए आपको किस काम में मदद चाहिए। मैं सरकारी सेवाओं के अगले कदम समझने में मदद कर सकता हूं।', chatReply: 'मैं इस अनुरोध के अगले कदम समझने में मदद कर सकता हूं। मिलती-जुलती प्रक्रिया और कार्य योजना देखने के लिए सेवा मार्गदर्शन जारी रखें।', continueGuidance: 'सेवा मार्गदर्शन जारी रखें',
  popular: 'लोकप्रिय सेवाएं', pickService: 'एक चुनें या ऊपर अपनी समस्या बताएं।', howWorks: 'LifeOS कैसे काम करता है', fromGoal: 'आपके लक्ष्य से पूरा होने तक, एक कदम एक समय पर।', nextStep: 'आपका अगला कदम', trackServices: 'अपनी सेवाएं ट्रैक करें और अगला काम देखें।', actionPlan: 'आपकी कार्य योजना', complete: 'पूरा', myLifeOS: 'मेरा LifeOS', activeServices: 'सक्रिय सेवाएं', pendingActions: 'बाकी काम', completed: 'पूरे हुए', upcoming: 'आने वाले', noActive: 'अभी कोई सक्रिय सेवा नहीं है।', startOne: 'शुरू करें', status: 'स्थिति', inProgress: 'जारी है', pending: 'बाकी', next: 'अगला', allDone: 'सब पूरा', continue: 'जारी रखें', documents: 'दस्तावेज़:', markDone: 'पूरा चिह्नित करें', undo: 'वापस करें', backServices: 'मेरी सेवाएं', backToServices: 'सेवाओं पर वापस जाएं', createPlan: 'कार्य योजना बनाएं', addToServices: 'मेरी सेवाओं में जोड़ें', officialService: 'आधिकारिक सेवा देखें', recommended: 'सुझाए गए अगले कदम', requiredInfo: 'ज़रूरी जानकारी', estimatedTime: 'अनुमानित समय', mode: 'तरीका', online: 'ऑनलाइन', demoOnly: 'केवल डेमो', documentQuestion: 'क्या आपके पास दस्तावेज़ है?', upload: 'PDF / JPG / PNG अपलोड करें', optionalDoc: 'वैकल्पिक। इस प्रोटोटाइप में कुछ भी ब्राउज़र से बाहर नहीं जाता।', documentReceived: 'दस्तावेज़ मिल गया', documentAnalyzed: 'दस्तावेज़ का विश्लेषण हुआ', consumerNumber: 'उपभोक्ता संख्या', billAmount: 'बिल राशि', billPeriod: 'बिल अवधि', remove: 'हटाएं', noNotifications: 'अभी कोई सूचना नहीं।', resetDemo: 'डेमो रीसेट करें', goHome: 'होम पर जाएं', backHome: 'होम पर वापस जाएं', language: 'भाषा', flow1: 'अपना लक्ष्य बताएं', flow2: 'सही आधिकारिक प्रक्रिया खोजें', flow3: 'कार्य योजना बनाएं', flow4: 'पूरा होने तक ट्रैक करें', helpBody: 'होम पेज पर अपनी समस्या लिखें या कोई सुझाव चुनें। LifeOS आधिकारिक प्रक्रिया दिखाता है, चेकलिस्ट बनाता है और उसे ट्रैक करने देता है।', notFoundHeading: 'अभी इसे पहचान नहीं पाए', notFoundBody: 'इस प्रोटोटाइप में बिजली, ड्राइविंग लाइसेंस और PAN की जानकारी है। कृपया इनमें से कोई चुनें।', understanding: 'आपकी बात समझ रहे हैं…', readMessage: 'आपका संदेश पढ़ रहे हैं', identifyService: 'सेवा पहचान रहे हैं', checkProcess: 'आधिकारिक प्रक्रिया देख रहे हैं', preparePlan: 'कार्य योजना तैयार कर रहे हैं',
}
const hg: Partial<Record<Key, string>> = {
  home: 'Home', services: 'Meri Services', track: 'Tasks Track Karo', help: 'Help', tagline: 'Aapka rozmarra ka service saathi', badge: 'Bharosemand service guidance', h1: 'Batao kya chahiye. Hum raasta dikhayenge.', sub: 'Apni problem apne words mein batao. LifeOS sahi official service, documents aur next steps samjhata hai.', ph: 'Aap kya karna chahte ho?', tryTxt: 'Aise bolo',
  exampleElectricity: 'Bijli bill', exampleLicence: 'Licence renewal', examplePan: 'PAN help', voiceInput: 'Voice se bolen', listening: 'Sun rahe hain', uploadDocument: 'Document upload karein', send: 'Search', inputError: 'Batayein aapko kis kaam mein madad chahiye.', attached: 'Attached',
  newChat: 'New chat', chatHistory: 'Chat history', aiName: 'LifeOS AI', chatWelcome: 'Batayein kis kaam mein help chahiye. Main supported public services ke next steps samjha sakta hoon.', chatReply: 'Main is request ke next steps samjhane mein help kar sakta hoon. Matching process aur action plan dekhne ke liye service guidance continue karein.', continueGuidance: 'Service guidance continue karein',
  popular: 'Popular Services', pickService: 'Ek choose karo ya upar problem batao.', howWorks: 'LifeOS kaise kaam karta hai', fromGoal: 'Aapke goal se completion tak, ek step ek baar.', nextStep: 'Aapka next step', trackServices: 'Apni services track karo aur next step dekho.', actionPlan: 'Aapka Action Plan', complete: 'Complete', myLifeOS: 'Mera LifeOS', activeServices: 'Active Services', pendingActions: 'Pending Actions', completed: 'Completed', upcoming: 'Upcoming', noActive: 'Abhi koi active service nahi hai.', startOne: 'Shuru karo', status: 'Status', inProgress: 'In Progress', pending: 'Pending', next: 'Next', allDone: 'Sab done', continue: 'Continue', documents: 'Documents:', markDone: 'Done mark karo', undo: 'Undo', backServices: 'Meri Services', backToServices: 'Services par wapas', createPlan: 'Action Plan banao', addToServices: 'Meri Services mein add karo', officialService: 'Official Service dekho', recommended: 'Recommended next steps', requiredInfo: 'Required information', estimatedTime: 'Estimated time', mode: 'Mode', online: 'Online', demoOnly: 'Demo only', documentQuestion: 'Document hai?', upload: 'PDF / JPG / PNG upload karo', optionalDoc: 'Optional. Is prototype mein file browser se bahar nahi jaati.', documentReceived: 'Document mil gaya', documentAnalyzed: 'Document analyze hua', consumerNumber: 'Consumer Number', billAmount: 'Bill Amount', billPeriod: 'Bill Period', remove: 'Remove', noNotifications: 'Abhi notifications nahi hain.', resetDemo: 'Demo reset karo', goHome: 'Home par jao', backHome: 'Home par wapas', language: 'Language', flow1: 'Apna goal batao', flow2: 'Sahi official process dhoondte hain', flow3: 'Action plan banate hain', flow4: 'Complete hone tak track karo', helpBody: 'Home page par problem likho ya koi suggestion chuno. LifeOS official process dikhata hai, checklist banata hai aur tracking mein help karta hai.', notFoundHeading: 'Abhi yeh match nahi hua', notFoundBody: 'Is prototype mein electricity, driving licence aur PAN flows hain. Inmein se koi ek try karo.', understanding: 'Aapki request samajh rahe hain…', readMessage: 'Message padh rahe hain', identifyService: 'Service identify kar rahe hain', checkProcess: 'Official process check kar rahe hain', preparePlan: 'Action plan prepare kar rahe hain',
}
export const dict = { en, hi, hg }
export type Dict = Record<Key, string>
/** Return localized copy, falling back to English when a translation is missing. */
export const tr = (lang: Lang, key: Key): string => dict[lang][key] ?? en[key]
export const localized = (lang: Lang): Dict => ({ ...en, ...dict[lang] })
